version: '3'
services:
  release:
    build:
      context: .
      dockerfile: ./docker/release/Dockerfile
      args:
        - HTTP_PROXY=${HTTP_PROXY}
        - HTTPS_PROXY=${HTTPS_PROXY}
        - WORK_DIR=${WORK_DIR}
    container_name: release
    tty: true
    environment:
      - HTTP_PROXY=${HTTP_PROXY}
      - HTTPS_PROXY=${HTTPS_PROXY}
